repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check --fix
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
        stages: [pre-commit]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types_or: [ python, pyi ]
        stages: [ pre-commit ]

      - id: check-yaml
        name: check-yaml
        entry: check-yaml
        language: system
        types: [yaml]
        stages: [pre-commit]
 
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: check-merge-conflict
        language: system
        types: [text]
        stages: [pre-commit]
 
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        stages: [pre-push]
 
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [pre-push]